### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [suclearnub/python-discord-rpc#3]
```
Traceback (most recent call last):
  File "./linux-rpc.py", line 21, in <module>
    rpc_obj.set_activity(activity)
  File "/home/connor/linux-rpc/rpc.py", line 138, in set_activity
    self.send(data)
  File "/home/connor/linux-rpc/rpc.py", line 117, in send
    self._write(data_bytes)
  File "/home/connor/linux-rpc/rpc.py", line 201, in _write
    self._sock.sendall(data)
BrokenPipeError: [Errno 32] Broken pipe
```
What should I do, catch this error and do `rpc.DiscordIpcClient.for_platform(app_id)` again?

**Comment by SIGSTACKFAULT** [comment]
...And I think I've figured out how to fix it!

```
$ diff rpc.py rpc_fix.py
```

```
116,117c116
<         self._write(header)
<         self._write(data_bytes)
---
>         self._write(header + data_bytes)
```
